import Head from 'next/head'
import { Inter } from 'next/font/google'
import { addApolloState, initializeApollo } from '@data/client'
import MoviesArchiveView, { MoviesViewQueries } from '@views/MoviesArchiveView'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MoviesArchiveView />
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const apolloClient = initializeApollo()

  // await for all queries
  await Promise.all(MoviesViewQueries.map((query) => apolloClient.query({
    query,
    variables: {},
  })))

  return addApolloState(apolloClient, {
    props: {},
  })
}