import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import MovieCard from '@components/MovieCard'
import MovieGrid from '@components/MovieGrid'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MovieGrid>
          { /* Loop over 5 times <MovieCard /> */ }

          {
            Array(5).fill(0).map((_, index) => {
              return (
                <MovieCard
                  title='test'
                  url='/test'
                  image={`https://picsum.photos/seed/picsum${ index }/400`}
                  description='Desciption'
                  year='2021'
                  />
              )
            })
          }
        </MovieGrid>
      </main>
    </>
  )
}
